version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    volumes:
      - ./src:/app/src
      - ./pom.xml:/app/pom.xml
    depends_on:
      - db  # Указываем зависимость от сервиса базы данных:cite[5]

  db:
    image: postgres:15  # Используем официальный образ PostgreSQL:cite[4]
    container_name: postgres-db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"  # Пробрасываем порт для подключения с хоста:cite[1]
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Том для сохранения данных:cite[5]

# Определяем том для постоянного хранения данных БД
volumes:
  postgres_data:
    driver: local